config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'

  get '/articles' => 'articles#index'
  get '/articles/new' => 'articles#new', as: 'new_article'
  post '/articles/create' => 'articles#create', as: 'create_article'
  get '/articles/edit' => 'articles#edit', as: 'edit_article'
  post '/articles/update' => 'articles#update', as: 'update_article'
  get '/articles/destroy' => 'articles#destroy', as: 'destroy_article'
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    validates :username, presence: true, 
                        uniqueness:true, 
                        length: {minimum:2}
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all.order(:id)
  end

  def new
  end

  def edit
    @articles = Article.all
    @id = params[:id].to_i
  end

  def create
    # @article = Article.new
    # @article.title = params[:title]
    # @article.content = params[:content]

    # if @article.save
    if Article.create(title: params[:title], author: 'JC', content: params[:content])
      redirect_to articles_path, notice: "back to index"
    else
      render :new
    end
  end

  def update
    article = Article.find(params[:id].to_i)
    if article.update(title: params[:title], content: params[:content])
      redirect_to articles_path
    else
      render :edit
    end
  end

  def destroy
    article = Article.find(params[:id].to_i)
    article.destroy
    redirect_to articles_path, alert: "blog post deleted"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :age, :username, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/create.html.erb
<h1>Articles#create</h1>
<p>Find me in app/views/articles/create.html.erb</p>

app/views/articles/destroy.html.erb
<h1>Articles#destroy</h1>
<p>Find me in app/views/articles/destroy.html.erb</p>

app/views/articles/edit.html.erb
<div class="row">
    <div class="col-lg-6 mx-auto">
                    
        <blockquote class="blockquote blockquote-custom bg-white p-5 shadow rounded">
        <h2>Edit blog post </h2>
        <%= form_with url: update_article_path do |f| %>
            <% @articles.each do |article| %>
                <% if @id==article.id %>
                    <p>
                        <%= f.label :id %><br/>
                        <%= f.text_field :id, value: article.id, readonly: true %>
                    </p>
                    <p>
                        <%= f.label :title %><br/>
                        <%= f.text_field :title, value: article.title, size: "50x2"%>
                    </p>
                    <p>
                        <%= f.label :content %><br/>
                        <%= f.text_area :content, value: article.content, size: "70x5" %>
                    </p>
                    <p>
                        <%= f.submit 'Update' %>
                    </p>
                <% end %>
            <% end %>
        <% end %>
        </blockquote>
                
    </div>
</div>

                    

app/views/articles/index.html.erb
<section class="py-5">
    <div class="container">
        <!---->
        <div class="row">
            <div class="col-lg-6 mx-auto">
                <header class="text-center pb-5">
                    <h1 class="h2">JC's blog</h2>
                    <p>--</p>
                </header>
            </div>
        </div><!-- END -->
        
        <% @articles.each do |article| %>
        <div class="row">
            <div class="col-lg-6 mx-auto">

                <!-- CUSTOM BLOCKQUOTE -->
                <blockquote class="blockquote blockquote-custom bg-white p-5 shadow rounded">
                    <h1><%= article.title %></h1>
                    <p class="mb-0 mt-2 font-italic"><%= article.content %></p>
                    <footer class="blockquote-footer pt-4 mt-4 border-top">
                        <%= article.author %>
                        <%= link_to 'edit', edit_article_path(id: article.id), class:'btn btn-info' %>
                        <%= link_to 'delete', destroy_article_path(id: article.id), class:'btn btn-info' %>
                    </footer>
                </blockquote><!-- END -->

            </div>
        </div>
        <% end %>
        <div class="row">
            <div class="col-lg-6 mx-auto">
                <header class="text-center pb-5">
                    <button type="button" class="btn btn-outline-dark .btn-lg"><%= link_to 'new article', new_article_path %></button>
                </header>
            </div>
        </div>
        >
    </div>
</section>

app/views/articles/new.html.erb
<div class="row">
    <div class="col-lg-6 mx-auto">
                    
        <blockquote class="blockquote blockquote-custom bg-white p-5 shadow rounded">
        <h2>Create new blog post</h2>
        <%= form_with url: create_article_path do |f| %>

            <p>
                <%= f.label :title %><br/>
                <%= f.text_field :title, size: "50x2"%>
            </p>
            <p>
                <%= f.label :content %><br/>
                <%= f.text_area :content, size: "70x5" %>
            </p>
            <p>
                <%= f.submit %>
            </p>

        <% end %>
        </blockquote>
                
    </div>
</div>

                    

app/views/articles/update.html.erb
<h1>Post successfully updated!</h1>
<%= link_to 'new article', new_article_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Username</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.age %></td>
        <td><%= user.username %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @user.age %>
</p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>